apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kubernetes.io/change-cause: "Update nginx to 1.10.2"
  name: nginx
  labels:
    name: nginx
spec:
  replicas: 5
  selector:
    matchLabels:
      name: nginx
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: nginx
    spec:
      containers:
      - image: nginx:1.10.2
        imagePullPolicy: Always
        name: nginx
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "500m"
            memory: "128Mi"
          limits:
            cpu: "1000m"
            memory: "256Mi"