apiVersion: v1
kind: Pod
metadata:
  name: kuard-tls
spec:
  containers:
  - name: kuard-tls
    image: gcr.io/kuar-demo/kuard-amd64:1
    imagePullPolicy: Always
    volumeMounts:
      - mountPath: /tls
        name: tls-certs
        readOnly: true
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
  imagePullSecrets:
    - name: my-image-pull-secret
  volumes:
    - name: tls-certs
      secret:
        secretName: kuard-tls
