apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: kuard
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "kuard"
      version: "2"
  template:
    metadata:
      labels:
        app: "kuard"
        version: "2"
    spec:
      containers:
      - image: gcr.io/kuar-demo/kuard-amd64:2
        name: kuard
      
